### PR TITLE
Replaced call to np.sqrt within Cython engine with libc.math cimport

### PR DESCRIPTION
**Pull request by aphearin**
Now avoiding the python-layer interaction in the cython engine

### CODE REVIEW

**Comment by aphearin** [comment]
@bsipocz and/or @eteq - do either of you know a workaround for this annoying problem of the `sqrt` function not being implemented in `libc.math` for windows platforms? I can't pass on AppVeyor without a workaround for this. Since it's a cython module, I can't compile with a `try...except` pattern

**Comment by bsipocz** [comment]
@aphearin - Sorry, I don't know much about this. cc-ing @MSeifert04 as he may run into this before.

**Comment by MSeifert04** [comment]
The failures on AppVeyor seem to be because of some `super` gone wrong, don't they? Do you have a link to an AppVeyor build that failed because of the missing `libc.math.sqrt`?

**Comment by aphearin** [comment]
@MSeifert04 - yes, the traceback is a little mysterious to me. But if you look at the diff, this PR only makes a single change on two lines: adding a line `from libc.math cimport sqrt as c_sqrt`, and then replacing `np.sqrt` with `c_sqrt`. This may not have been obvious since there are trivial PEP8-related changes imposed by my text editor.

**Comment by MSeifert04** [comment]
Could you run the tests with the `sqrt` changes reverted and only containing the PEP8 changes? It wouldn't be the first time something else broke with the conda packages that had nothing to do with a PR.

**Comment by MSeifert04** [comment]
It seems the [reversed "commit" also failed](https://ci.appveyor.com/project/Astropy/halotools/build/1.0.691) so this is likely not a problem of `libc.math.sqrt` on appveyor.

**Comment by aphearin** [comment]
Yes, I just noticed that. Thanks for the suggestion. Looking into it now.

**Comment by bsipocz** [comment]
@aphearin - I've restarted a rebuild on the current master here, as it may be possible that even that one is failing: https://ci.appveyor.com/project/Astropy/halotools/build/1.0.693

**Comment by aphearin** [comment]
@bsipocz - good idea to just check master. Looks like that is indeed what is going on.

**Comment by aphearin** [comment]
Closing this PR since @duncandc is rewriting this engine in several other ways and is aware of the `np.sqrt` issue

**Pull request closed without merging**
