### PR TITLE
adding rp_pi_tpcf_jackknife function to mock_observables 

### PR DESCRIPTION
**Pull request by duncandc**
This pull requests add a jackknife version of the rp_pi_tpcf function.  This feature was requested by @givoltage and discussed in #244.

This function is slightly more complicated than the other jackknife functions.  The observable had to be flattened in order to calculate the covariance matrix.  I would feel more comfortable if someone tries out this function before we fully merge it into master.

### CODE REVIEW

**Comment by aphearin** [comment]
@givoltage - have you had a chance to play with this feature for your application yet? We will soon be releasing `v0.6` and were hoping you would be able to provide independent science validation

**Comment by givoltage** [comment]
Thanks much for implementing it. I ran the function successfully without any issue and was going to configure a BAO fit to the output files to see the results. I don't feel quite qualified to comment on the scientific validity of the results now. The only thing I noticed which may or may not be a shortcoming is that output xi_cov is a 2D matrix which takes a little effort to figure out the flattening and indexing convention; a 4D matrix with shape (n_rp_bins-1, n_pi_bins-1, n_rp_bins-1, n_pi_bins-1) would be more straightforward in referencing the cov value to the two bins. But I'm not an expert and maybe there are many reasons why keeping it 2D is desirable.

**Comment by aphearin** [comment]
Thanks for the feedback @givoltage. I think the jackknife function should return a 2D covariance matrix for consistency with the other jackknife functions in `mock_observables`, but I'd be happy to add a few lines to the docs so that users have a simple copy-and-paste one-liner to transform the returned 2D matrix into the 4D matrix that you find more intuitive. Would you be willing to provide the relevant code snippet that performs the flattening and ndarray manipulations that you mentioned? I'm going to go ahead and merge this PR, but I'm happy to alter the docs in a later PR if you could provide the code snippet.

**Comment by givoltage** [comment]
I did not convert the output 2D xi_cov to a 4D array--once I figured out the indexing convention I just took and manipulated the data directly. Thanks.

**Pull request merged**
