### PR TITLE
Add empty appveyor.yml file to repo

### PR DESCRIPTION
**Pull request by aphearin**
Committing an empty configuration file for appveyor

### CODE REVIEW

**Comment by aphearin** [comment]
Merging this PR sets up the AppVeyor continuous integration service. Thanks to @embray for pointing me in the right direction to get this going. 

This PR resolves #389 and #385. 

Additional commits that improve the robustness of the test suite also bring windows-compatibility to Halotools, including a fully passing test suite. Thanks to @a-kravtsov for helping track down the problems causing the incompatibility. Now that AppVeyor is set up, it should be straightforward to maintain windows compatibility as the code evolves.

**Comment by bsipocz** [comment]
I'm sorry @aphearin for not replying to this and #389 earlier. 

In the ``appveyor.yml`` you can use the custom version assignments (as in travis), so it may be more convenient to test againts ``stable`` astropy and numpy, and you can do tests against python3, too.

**Comment by aphearin** [comment]
No problem at all, @bsipocz . I just pattern-matched the `appveyor.yml` file in the latest helpers and that did the trick. My Travis runners handle many different system setups, so I'm not sure that doing the same thing on AppVeyor is necessary, but if your experience tells you otherwise then I'm definitely open to making the windows-based testing suite more elaborate.

**Comment by bsipocz** [comment]
@aphearin - yes, I agree that there's no need for that many setups for appveyor. However maybe adding a py3 build wouldn't hurt (or if having only one build, be it a 3.5 rather than a 2.7).

**Comment by aphearin** [comment]
@bsipocz - my 3.x compatibility is still in the "aspirational" stage, so if I only had a 3.5 build, all appveyor checks would fail. Probably I should just set it up the way my travis is setup, such that I do a 3.5 build but mark it as an allowed failure.

**Comment by bsipocz** [comment]
Ohh, I didn't notice, sorry. Good luck with getting the compatibility, hopefully it'll be painless (and not like the old pipeline and its dependencies I've spent the last week, without much success).

**Pull request merged**
