### PR TITLE
Resolve issue #577: modulate_with_cenocc changed to cenocc_model

### PR DESCRIPTION
**Pull request by mclaughlin6464**
Fixes issue #577. At the time of this request it is still under debate whether this change is appropriate. However, I believe this is the most natural way to resolve a bug in the way Zheng07Sats handles central modulation. 

Please note I have not run the test modules as my local setup does not support it. I can possible run later, but it would be helpful if someone else could check.

### CODE REVIEW

**Comment by aphearin** [comment]
Thanks @mclaughlin6464 - I'll give this a careful review right after the holiday.

**Comment by mclaughlin6464** [comment]
It would appear that the `leauthaud11` model has similar functionality to `zheng07`. It seems we should update that one as well; I'm happy to implemented the same features we have for `zheng07` over the weekend.

**Comment by mclaughlin6464** [comment]
I don't understand the Assembly bias functionality enough to fix this error. I think you'll have to take a look at this @aphearin . No rush.

**Comment by aphearin** [comment]
No problem @mclaughlin6464 - nice work getting it down to just one remaining failure. The HeavisideAssembias class is pretty dense; I didn't see a long-term future in building upon this simple two-population family of toy models, so I didn't bother to make it super extensible. I'll fix the remaining failure next week.

**Pull request merged**
