### PR TITLE
Update Cacciato09Cens

### PR DESCRIPTION
**Pull request by alanxuhaojie**
Add 'prim_galprop_max' keyword arguments in Cacciato09Cens

### CODE REVIEW

**Comment by aphearin** [comment]
Thanks for the PR @alanxuhaojie! I added a simple unit-test but otherwise nice job on taking the time to write docstrings and clean code. This looks like a useful feature.

**Comment by alanxuhaojie** [comment]
@aphearin Wrong sign in the return statement with prim_galprop_max keyword added. It should work now.

**Review by alanxuhaojie — COMMENTED** [review]
Nice unit-test on prim_galprop_max keyword argument.

**Review by aphearin — COMMENTED** [review]
Thanks for catching my mistake in the unit-test, and fixing it up with this clear explanation. Much appreciated!

**Comment by aphearin** [comment]
Nice work all around on this PR @alanxuhaojie, and special thanks for helping with the unit-testing. I'm happy to have this nice feature in the CLF code!

**Pull request merged**
