### PR TITLE
Making py3 compatible aph edits

### PR DESCRIPTION
**Pull request by aphearin**
@bsipocz - I finally resolved the bug that was causing your PR to fail on my local tests. So this PR introduces full-fledge python 3.x compatibility, at long last. 

However, I am a bit mystified by the resolution, and I don't want to merge the PR until I understand it. As shown in this commit, https://github.com/aphearin/halotools/commit/469a7f96c2202ffedc75198dd82d49977a47b128, all I had to do is wrap `yield_entry` with the `bool` function. Without doing this, `yield_entry` stores an integer, and so the way the concluding control flow *was* written, the generator always yielded an empty list, causing test failures that are local to my machine where my local cache.log is *not* empty. What I'm confused about is what change led to this. Why did this only crop up now? Let me know if you have any insight. I'll be glad to put this PR into the repo when I get to the bottom of it.

### CODE REVIEW

**Comment by aphearin** [comment]
Ok, I see it now @bsipocz. Some of the changes included changing `condition == True` to `condition is True`. This change is responsible for the difference because `(1 == True) is True` but `(1 is True) is False`. Mystery resolved, PR ready to merge, huzzah!

**Comment by aphearin** [comment]
This PR resolves #266 and #190.

**Comment by aphearin** [comment]
many thanks, @bsipocz!

**Comment by bsipocz** [comment]
@aphearin - Sorry about this PEP8 mess, I should have read the code to figure out what it does and use e.g. this change instead of ``is True``:

```
if yield_entry:
    yield entry
```

It should have the same output as the current version with ``bool()``, however I think it's better readable with ``bool()``.

**Comment by aphearin** [comment]
No problem at all, this is entirely on me because some tests only run on my personal machine and this error does not get caught unless the APH_MACHINE flag in my test suite is True.

**Pull request merged**
