### PR TITLE
Updated setup.cfg

### PR DESCRIPTION
**Pull request by aphearin**
Now using tool:pytest, replacing deprecated pytest section

### CODE REVIEW

**Comment by aphearin** [comment]
@bsipocz - have you seen this `INTERNAL_ERROR` in any other affiliated packages? This failure only shows up in 3.3 builds of halotools.

**Comment by bsipocz** [comment]
Yes, that's because the test infrastructure is not yet compatible with the changes in pytest 3.2. 

We currently limit the pytest version in ci-helpers, so noone should face them. However you seem to run into other conda/pip fallbacks due to the np and astropy version that result a pytest upgrade and the <3.2 limitation then is not taken into account any more. 

The easiest workaround is to run that test job with astropy 1.3.x rather than stable as the 2.0.x releases are not even supposed to work with python 3.3 any more.

**Comment by bsipocz** [comment]
Oh, a more proper workaround is though is something like the following until astropy 2.0.2 is out (that contains a proper fix): https://github.com/bsipocz/photutils/commit/938fad7f546aeab94838642a512db58af605f7e3

However that kwarg was new in astropy 2.0, so it won't work with any older versions.

**Comment by aphearin** [comment]
Looks like your simple workaround did the trick. Thanks @bsipocz!

**Pull request merged**
