### PR TITLE
Add Simulation image to top bar

### PR DESCRIPTION
**Pull request by eteq**
This alters the halotools docs to add an nbody simulation image to the top bar, as @aphearin and I discussed offline.  You can see how it looks when generated at http://eteq.github.io/halotools/ .

I can't claim credit for figuring out how to make this work - I copied the trick of a customized css that inherits from the astropy style from gammapy (thanks @cdeil!)

@aphearin - I actually cut out a strip from the file you pointed me to, rather than the whole thing - the whole thing was 1.5M, and that would make all visitors to the docs page have to download that whole file.  The strip I cut out here is a more manageable 150K.  If there's some other chunk of that image you'd like to chop out, feel free to PR against this branch or otherwise send it to me.  Also, this image should probably be credited somewhere.  Where do you want me to put that? (or, again, feel free to issue a PR against my add-haloimg-topbar branch).

### CODE REVIEW

**Comment by eteq** [comment]
@aphearin - as per our e-mail discussion, I've added mention of Ralf and KIPAC, right now on the front page because I didn't see a credits page in the documentation.  I can easily put it elsewhere if you want, though. (Or this can be merged and that changed later).

**Comment by aphearin** [comment]
I think that's fine for now. Ralf didn't seem too worked up about this. Feel free to either go ahead and merge, or charge me with doing it, subject to the following caveat. I could handle the merge myself, but before doing so I would want to know the answer to my question in #58 about how GitHub handles multiple PRs, some with a time lag.

**Comment by eteq** [comment]
@aphearin - re: your question in #58 and how it pertains to this PR: if you merge this now it looks like it won't conflict at all with #58 because none of the same files are altered by these PRs.  So this should be safe to merge right now without affecting anything else, but I'll leave it to you to do that to make sure you're ok with it.

**Comment by aphearin** [comment]
Rebase. Got it. I read about this command in a git tutorial months ago and have never used it, but this is exactly the functionality I was asking about. Thanks for the tip. I'll read up on it.

**Pull request merged**
