### PR TITLE
MAINT: remove usage of removed astropy functionality _find_home()

### LINKED ISSUE #1106: BUG: compatibility issues with astropy 7.0
I'm fairly certain that there are compatibility issues with astropy 7.0 as I see hints for it in a recent migration triggered conda-forge build: https://github.com/conda-forge/halotools-feedstock/pull/29

I don't see any development version testing, or regular cron jobs to confirm this, but one clear issue is the usage of some removed functionality, e.g. `astropy.config._find_home()`

### PR DESCRIPTION
**Pull request by bsipocz**
This should hopefully fix #1106

### CODE REVIEW

**Comment by bsipocz** [comment]
cc @aphearin - this should be good to go now, and maybe could be included in a quick bugfix release that fixes astropy 7.0 compatibility.

**Comment by aphearin** [comment]
Thanks for this fix @bsipocz! I'm glad you were able to pinpoint this issue with setuptools, and separate this bug from the ongoing [unresolved bug with Numpy 2.0 incompatibility](https://github.com/astropy/halotools/issues/1084), which may take longer to resolve. The source of the Numpy 2.0 incompatibility looks like the way the cython kernels are written, but I haven't gotten to the bottom of that yet. And so since your fix in this PR works in standalone fashion, maybe we should proceed with this merge and then turn attention to the cython/extension-helpers/etc - do you agree?

**Comment by bsipocz** [comment]
Yes, I agree that these should be handled separately. Saying that it's not yet numpy2.0 compatible is totally legitimate, but there is no reason for not to be astropy 7 compatible when it's all just silly API cleanups that shouldn't have happened without due notice of downstream.

**Comment by aphearin** [comment]
Great, yes, that's what I thought too - thanks for confirming.

**Pull request merged**
