### PR TITLE
Delta sigma from 2d

### PR DESCRIPTION
**Pull request by aphearin**
New implementation of `delta_sigma` function, including API change. Function is more accurate than v0.4 implementation, numerically more stable, faster, and has been generalized to work with simulations that include particles of variable mass, such as hydro or sims with massive neutrinos, resolving #629. 

Special thanks to @surhudm for providing an independent implementation of delta sigma, now included in the unit-testing suite to verify code correctness. 

CC @duncandc @sssaito

### CODE REVIEW

**Comment by surhudm** [comment]
@aphearin One quick suggestion for enhancement would be to project along a
given axis rather than z axis alone.

**Comment by aphearin** [comment]
You mean, to help beat down sample variance? Or some other motivation?

**Comment by surhudm** [comment]
Yes, although these are not exactly independent projections...

**Comment by aphearin** [comment]
Exactly, it would be effectively impossible to quote error bars this way.

**Pull request merged**
