### PR TITLE
Updated Travis to remove allow_failures

### PR DESCRIPTION
**Pull request by souravsingh**
Removed allow_failures to help Travis run 3.x tests

### CODE REVIEW

**Comment by aphearin** [comment]
Hi @souravsingh - the reason for permitting 3.x failures at this stage in Halotools development is that the current code fails 3.x compatibility, but I want to continue being able to use Travis while I work towards 3.x compatibility, and I don't want to halt all development until this is resolved. Is there a particular reason you submitted this PR?

**Comment by souravsingh** [comment]
I saw the open issue at #266 which mentioned about removing the section in Travis.

**Comment by souravsingh** [comment]
I can close the PR if it isn't needed

**Comment by aphearin** [comment]
Ahh, ok, yes, thanks. #266 actually comments that this PR should only be made and merged *after* 3.x compatibility is achieved. If this PR were merged in now, then Travis would fail until compatibility goes through, which is not currently a pressing priority. 

I could leave this PR open since you are correct that this is exactly what needs to be done once Halotools is 3.x compatible, but #266 is already serving as a marker to help me remember to do this, so I'll go ahead and close this for now but reopen it and go through with the merge whenever Halotools is 3.x compatible. Thanks for submitting the PR though.

**Pull request closed without merging**
