### PR TITLE
Addressed issue #765, changed default halo mass definition for Caccia…

### PR DESCRIPTION
**Pull request by johannesulf**
…to09, added column to FakeSim to work with Cacciato09 by default

### CODE REVIEW

**Comment by aphearin** [comment]
@johannesulf - have you verified the little-h convention used in halo mass definition is consistent as well? Otherwise, PR looks good.

**Comment by johannesulf** [comment]
@aphearin Cacciato+09 use the usual little-h convention (halo mass in h^{-1} M_\odot) also employed by halotools. So this looks fine.

**Comment by surhudm** [comment]
Hi guys,

Just a quick note: At the time we worked on Cacciato et al 2009, we were
quite unaware of the overdensity problems of FOF halos. So the analytical
model assumes an overdensity of 180b for FOF halos with b=0.2 (whose mass
function and clustering enters the model). In reality the treatment is
inconsistent because we are using halos with higher overdensity (see my
2011 paper with Andrey, as well as cautionary note in Warren 2006) given
the mass function and bias we use, but assuming that they are 180b. A note
should be added somewhere to this effect in the docs. I think this
difference is way larger than the 180b, 200b issue.

I would suggest replacing Cacciato 09 with the more recent Cacciato 2013
model which is based on 200b SO halos, but has a much more consistent
treatment.

Surhud

**Comment by aphearin** [comment]
Well, the models under discussion here have best-fit values that were calibrated using analytical halo models, so their one-to-two halo transitions will differ from the corresponding Halotools prediction even in cases where the same halo mass definition is identical. Users requiring genuinely high-accuracy one-to-two halo transitions will need to refit the parameters of any model that is based on any existing fitting function. Since the pre-built models cannot even in principle reproduce analytical HOD results for this reason, I see little cause to worry too much about this.

**Pull request merged**
