### PR TITLE
Fix readthedocs formatting issues

### PR DESCRIPTION
**Pull request by aphearin**
As noticed by @pllim a recent PR (probably #1093) broke the readthedocs formatting. This PR attempts to fix.

### CODE REVIEW

**Comment by pllim** [comment]
Nope... See rendered doc at https://halotools--1095.org.readthedocs.build/en/1095/

**Comment by pllim** [comment]
Maybe you are not using the theme that you think you are using. Raw log might give you more info. Example: https://readthedocs.org/api/v2/build/25571238.txt

**Comment by pllim** [comment]
BTW, if you want to save CPU cycles for CI, you can put `[ci skip]` on your commit message. Actions respects that and won't run. RTD does not, so it would run anyway.

**Comment by pllim** [comment]
Looks good now. Glad you figured it out! 🎉 

https://halotools.readthedocs.io/en/latest/

**Comment by aphearin** [comment]
Yes! Mysteriously, it was just this one-liner: e94ce2aea7d87f21d830c98c93718451c40342e9. Thanks again for all the help @pllim!

**Pull request merged**
