### PR TITLE
Improving npairs(s, mu) performance and testing.

### PR DESCRIPTION
**Pull request by manodeep**
Completely un-tested, un-benchmarked. I am assuming there are existing tests for the npairs(s, mu) pair counters. 

Related to #763

### CODE REVIEW

**Comment by duncandc** [comment]
Performance is about 10x's worse for me when applying this code.  Are there some compiling flags that we need implement?

**Comment by aphearin** [comment]
Cython's automated compiler flags are sufficiently good that a 10x improvement never occurs by simply adding flags. If you just run `cython -a` on the module, it showed that there were a couple of forgotten declarations that I just added just now.

**Comment by duncandc** [comment]
Excellent.  That did the trick.  It looks to be of order 50% performance increase over the code in the repo right now.   Im going to push my modifications to the pair counters and tests to this PR.

**Comment by duncandc** [comment]
Okay, I plan on merging this with master after it passes the travis build.  I think the brute force pairs.s_mu_npairs comparison test should alleviate any concern that may have been lingering about the reliability of the optimized npairs_s_mu() function.  I have also edited the doc strings of the s_mu pair counters.

**Comment by duncandc** [comment]
@aphearin do you expect some travis builds to fail currently?

**Comment by duncandc** [comment]
okay, note that doc strings with math need to be preceded by an 'r' in order to pass python 3 builds.

**Pull request merged**
